### ISSUE TITLE
Progress Tracker: Tree & Node class methods

### ISSUE THREAD

**Issue by klaudiosinani** [klaussinani/binstree#3]
## Description

The following issue will act as a progress tracking thread, regarding the implementation of the exposed `Tree` & `Node` class methods:

### Tree Methods

- [x] `Tree#insert(key, value)`
- [x] `Tree#isEmpty()`
- [x] `Tree#includes(key)`
- [x] `Tree#max()`
- [x] `Tree#min()`
- [x] `Tree#search(key)`
- [x] `Tree#remove(key)`
- [x] `Tree#inOrder(fn)`
- [x] `Tree#outOrder(fn)`
- [x] `Tree#postOrder(fn)`
- [x] `Tree#preOrder(fn)`
- [x] `Tree#toArray()`
- [x] `Tree#size()`
- [x] `Tree#levelOrder(fn)`
- [x] `Tree#height()`
- [x] `Tree#isBalanced()`
- [x] `Tree#isComplete()`
- [x] `Tree#internalNodes()`
- [x] `Tree#fullNodes()`
- [x] `Tree#leafNodes()`
- [x] `Tree#isFull()`
- [x] `Tree#isPerfect()`
- [x] `Tree#partialNodes()`
- [x] `Tree#clear()`

### Node Methods

- [x] `Node#degree`
- [x] `Node#key`
- [x] `Node#right`
- [x] `Node#left`
- [x] `Node#children`
- [x] `Node#isLeaf()`
- [x] `Node#isInternal()`
- [x] `Node#height()`
- [x] `Node#isFull()`
- [x] `Node#isPartial()`
- [x] `Node#isLeftPartial()`
- [x] `Node#isRightPartial()`
